paths:
  uploads: uploads # The default location for newly uploaded files, relative to source
  # collections: items # The path to the root collections folder, relative to source (automatically read from Jekyll if not set in the global configuration file)
  data: _data # The path to site data files, relative to source (automatically read from Jekyll if not set in the global configuration file)
  layouts: _layouts # The path to site layout files, relative to source (automatically read from Jekyll if not set in the global configuration file)
  # includes: _partials # The path to site include files, relative to source (automatically read from Jekyll if not set in the global configuration file)


# https://cloudcannon.com/documentation/articles/defining-your-collections/?ssg=Jekyll
collections_config:
  newsletters:
    # path: _innovation-lab-newsletters
    name: InnovationLab Newsletters
    description: The Innovation Lab Newsletter Email
    sort:
      key: date
      order: desc
    sort_options:
      - key: date
        label: Oldest to Newest
      - key: date
        order: desc
        label: Newest to Oldest
      - key: title
        label: By Title
    preview:
      subtext:
        - key: date
    _enabled_editors:
      - visual
      - content
      - data
    output: true
    # permalink: /il-newsletters/:path/
    singular_name: Newsletter
    singular_key: title
    icon: newspaper
    add_options:
      - name: New blank
        icon: add_box
      - name: New with content
        schema: prepopulated
        icon: post_add
      - name: TEST 1
        schema: test1
        icon: post_add
      - name: TEST 2
        schema: test2
        icon: post_add
    schemas:
      default:
        name: Blank
        path: schemas/newsletter_blank.md
        # create:
        #   path: news/{date|year}/{date|month}/{slug}[count].md
      prepopulated:
        name: Pre-Populated
        path: schemas/newsletter_prepopulated.md
      test1:
        name: Pre-Populated
        path: schemas/test1.md
      test2:
        name: Pre-Populated
        path: schemas/test2.md
    _inputs:
      layout:
        type: select
        options:
          values:
            - newsletter_default
            - newsletter_alternate



# data_config controls what data sets are available to populate select and multiselect inputs.
# If set as a boolean and true, all auto-discoverable data sets are added. This is only applicable to Jekyll and Hugo sites.
# If set as an object, only those data sets are added.
data_config:
  # authors: true # Populates data with authors from an data file with the matching name
  # offices: true


_inputs:
  permalink:
    comment: proper permalink format example:// /about/team
  copy_html:
    label: Copy
    type: html
  left_column_percent:
    label: Left column percent
    comment: Percentage width of the left column relative to the content width.
    type: range
    options:
      step: 1
      max: 100
      min: 0
  button_width:
    label: Button Width
    comment: Fixed Pixel width of the button. (Required for display in MS Outlook.)
    type: range
    options:
      step: 1
      max: 500
      min: 50
  il_newsletter_background_color:
    label: Background Color
    type: select
    options:
      values: _select_data.il_bg_colors
      value_key: key
      preview:
        text:
          - key: display_name
  il_newsletter_button_bkg_color:
    label: Button Background Color
    type: select
    options:
      values: _select_data.il_button_bg_colors
      value_key: key
      preview:
        text:
          - key: display_name
  il_newsletter_button_text_color:
    label: Button Text Color
    type: select
    options:
      values: _select_data.il_button_text_colors
      value_key: key
      preview:
        text:
          - key: display_name
  newsletter_sections:
    label: Innovation Lab Newsletter
    type: array
    options:
      structures: _structures.newsletter_sections # This structure is defined below under "_structures"

_select_data:
  il_bg_colors:
    - key: '#f8f8f6'
      display_name: Light Gray
    # - key: '#aacb65'
    #   display_name: Green
    - key: 'transparent'
      display_name: Transparent
  il_button_bg_colors:
    - key: '#f8f8f6'
      display_name: Light Gray
    - key: '#2c2c30'
      display_name: Dark Gray
    - key: '#aacb65'
      display_name: Green
    - key: '#cc0000'
      display_name: Red
  il_button_text_colors:
    - key: '#f8f8f6'
      display_name: Light Gray
    - key: '#2c2c30'
      display_name: Dark Gray
    - key: '#aacb65'
      display_name: Green
    - key: '#0000CC'
      display_name: Blue



# ARRAY STRUCTURES
# This is an example of how we can use array structures to allow the admin to add dynamic blocks.
# https://cloudcannon.com/documentation/articles/migrating-to-input-configuration/?ssg=Jekyll#structures
# https://cloudcannon.com/blog/managing-complex-content-with-array-structures/#:~:text=What%20are%20Array%20Structures%3F,to%20create%20their%20own%20pages.
_structures:
  dynamic_blocks: # see the "_input" config for "page_blocks" above.
    # style: modal
    values:
      - label: Text Block
        icon: ballot
        value:
          _id: text_block
          title:
          content_markdown:
          image:
      - label: Testimonial
        icon: format_quote
        value:
          _id: testimonial
          name:
          quote:
          company:
          photo_image:
      - label: Slideshow
        icon: collections
        value:
          _id: slideshow
          slides: []
  newsletter_sections: # see the "_input" config for "newsletter_sections" above.
    values:
      - label: Image, Headline, Text, CTA
        icon: format_align_center
        comment: Image left with text wrapped
        value:
          _type: headline_copy_cta
          headline:
          copy_html:
          background-color:
          image:
          cta:
            label:
            url:
            background-color:
            text-color:
            width:
      - label: Team Member Spotlight
        icon: account_circle
        comment: Features a team member with an image
        value:
          _type: teammember_spotlight
          headline:
          preheader:
          copy_html:
          image:
            image_src:
            image_caption:
            image_alt:
          icon_image:
          left_column_percent:
          il_newsletter_background_color:
      - label: Link Card list with Images
        icon: view_list
        comment: Stacked cards with image on left and title & description on right.
        value:
          _type: link_list_with_images
          headline:
          links:
            - headline:
              excerpt:
              image:
              link:
          cta_button:
            label:
            url:
            il_newsletter_button_bkg_color:
            il_newsletter_button_text_color:
            button_width:
            left_column_percent:
      - label: Events
        icon: event
        comment: Events List
        value:
          _type: events
          headline:
          events:
            - headline:
              date:
              copy_text:
              image:
              cta_label:
              cta_url:

      - label: Articles
        icon: article
        comment: List of article links. Each article shows headline, excerpt, author and date
        value:
          _type: articles
          headline:
          articles:
            - headline:
              url:
              copy_text:
              date:
              author_name:
              author_image:
      - label: Links list right, headline left
        icon: link
        comment: List of links, with the headline in the left column
        value:
          _type: link_list_with_dates
          headline:
          links:
            - headline:
              url:
              date: