paths:
  uploads: uploads # The default location for newly uploaded files, relative to source
  # collections: items # The path to the root collections folder, relative to source (automatically read from Jekyll if not set in the global configuration file)
  data: _data # The path to site data files, relative to source (automatically read from Jekyll if not set in the global configuration file)
  layouts: _layouts # The path to site layout files, relative to source (automatically read from Jekyll if not set in the global configuration file)
  # includes: _partials # The path to site include files, relative to source (automatically read from Jekyll if not set in the global configuration file)


# https://cloudcannon.com/documentation/articles/defining-your-collections/?ssg=Jekyll
collections_config:
  il-newlsletters:
    name: InnovationLab Newsletters
    _enabled_editors:
      - visual
      - content
      - data
    output: true
    singular_name: Newsletter
    singular_key: title
    description: The Innovation Lab Newsletter Email
    icon: newspaper
    add_options:
      - name: Create Another Newsletter
        icon: post_add

  examples:
    name: Examples
    _enabled_editors:
      - visual
      - content
      - data
    output: true
    subtext_key: role
    # image_key: featured_image
    # image_size: cover
    singular_name: Example
    singular_key: title
    disable_add: false
    description: Collection of some sandbox examples.
    # documentation:
    #   url: https://example.com/documentation
    #   text: Read the documentation here.
    icon: cruelty_free
    add_options:
      - name: Add Another Example Page
        icon: kayaking



# data_config controls what data sets are available to populate select and multiselect inputs.
# If set as a boolean and true, all auto-discoverable data sets are added. This is only applicable to Jekyll and Hugo sites.
# If set as an object, only those data sets are added.
data_config:
  # authors: true # Populates data with authors from an data file with the matching name
  # offices: true

# These inputs are for demonstration purposes. See implementation on src/examples/testconfig.html
_inputs:
  permalink:
    comment: proper permalink format example:// /about/team
  copy_html:
    label: Copy
    type: html
  example_input_2:
    label: This Input Should Be an Image
    type: image
  example_input_3:
    label: This Input Should Be an Select
    type: select
    options:
      values:
        - Bolt
        - Nut
        - Gear
  example_input_4:
    label: This Input Should Be an Multi Select
    type: multiselect
    options:
      values:
        - Wisconsin
        - Minnesota
        - north Dakota
        - Iowa
        - Illinois
        - South Dakota
  example_cards:
  page_blocks:
    label: Dynamic page blocks
    type: array
    options:
      structures: _structures.dynamic_blocks # This structure is defined below under "_structures"
  il_newsletter_sections:
    label: Innovation Lab Newsletter
    type: array
    options:
      structures: _structures.il_newsletter_sections # This structure is defined below under "_structures"



# ARRAY STRUCTURES
# This is an example of how we can use array structures to allow the admin to add dynamic blocks. See examples/testconfig.html
# https://cloudcannon.com/documentation/articles/migrating-to-input-configuration/?ssg=Jekyll#structures
# https://cloudcannon.com/blog/managing-complex-content-with-array-structures/#:~:text=What%20are%20Array%20Structures%3F,to%20create%20their%20own%20pages.
_structures:
  dynamic_blocks: # see the "_input" config for "page_blocks" above.
    # style: modal
    values:
      - label: Text Block
        icon: ballot
        value:
          _id: text_block
          title:
          content_markdown:
          image:
      - label: Testimonial
        icon: format_quote
        value:
          _id: testimonial
          name:
          quote:
          company:
          photo_image:
      - label: Slideshow
        icon: collections
        value:
          _id: slideshow
          slides: []
  il_newsletter_sections: # see the "_input" config for "il_newsletter_sections" above.
    values:
      - label: Image, Headline, Text, CTA
        icon: format_align_center
        comment: Image left with text wrapped
        value:
          _type: headline_copy_cta
          headline: Title of Section
          copy_html: Lorem ipsum dolor sit amet, consect etuer adipiscing elit, sed diam non ummy nibh euismod tinciduntg ut laoreet dolore manga aliuam erat volutpat. Ut isi wnim ad moinim veniam, uis nnostruc exerci tation ullamcorper suspicit.
          background-color: transparent
          image:
          cta:
            label: Click Here
            url:
            background-color: '#aacb65'
            text-color: '#2c2c30'
            width: 177
      - label: Link Card list with Images
        icon: view_list
        comment: Stacked cards with image on left and title & description on right.
        value:
          _type: link_list_with_images
          headline:
          cta:
            label: Explore All Initiatives
            url: https://lab.cr.org/initiatives/
            background-color: '#2c2c30'
            text-color: '#aacb65'
            width: 177
          cards:
            - headline:
              description:
              image:
      - label: Team Member Spotlight
        icon: account_circle
        comment: Features a team member with an image
        value:
          _type: teammember_spotlight
          name:
          image:
      - label: Events
        icon: event
        comment: Events List
        value:
          _type: events
          image:
      - label: Articles
        icon: article
        comment: Single Column Content Section
        value:
          _type: articles
          block_html:
      - label: Links list right, headline left
        icon: link
        comment: Two Column Images
        value:
          _type: link_list_with_dates
          images:
  slides:
    values:
      - label: Slide
        icon: collections
        value:
          image:
          caption: