# ATTENTION: ALL CLOUDCANNON CMS CONFIGURATION NOW LIVES IN cloudcannon.config.yml

# ------------------------------------------------
# DEFINE GLOBAL VARIABLES
# ------------------------------------------------

# Site settings
client: TBD
title: Ocupop Project Template
description: This description also used for social share meta
email: dev@ocupop.com
url: "http://client_url.com"
permalink: pretty

# Social sharing
socialshare:
  featured_image:
  twitter:
    username:
    image:

# Google Analytics
analytics:
  default:

placeholder_image: https://via.placeholder.com/1000x1000/333333/000000?text=Placeholder


# ------------------------------------------------
# DEFINE COLLECTIONS
# (All CloudCannon CMS config is set in cloudcannon.config.yml)
# ------------------------------------------------
collections:
  # il-newsletters:
  #   output: true
  #   permalink: /il-newsletters/:path/
  examples:
    output: true
    permalink: /examples/:path/


# ------------------------------------------------
# DEFINE DEFAULT VALUES
# (useful for setting layout for page types without having them editable by the user)
# ------------------------------------------------
defaults:
  -
    scope:
      type: 'page'
    values:
      layout: default
  -
    scope:
      type: 'post'
    values:
      layout: default
  -
    scope:
      type: 'examples'
    values:
      layout: sandbox
  -
    scope:
      type: 'il-newsletters'
    values:
      layout: email
      # variable_name: value


# ------------------------------------------------
# BUILD SETTINGS AND PLUGINS
# ------------------------------------------------
safe: false
sass:
  # style: compressed
  sass_dir: _scss
plugins:
  - jekyll-sitemap

_array_structures:
  il_newsletter_sections:
    - label: Simple headline, text, image and CTA ~
      icon: format_align_center
      comment: Image left with text wrapped
      value:
        _type: headline_copy_cta
        headline: Title of Section
        copy: Lorem ipsum dolor sit amet, consect etuer adipiscing elit, sed diam non ummy nibh euismod tinciduntg ut laoreet dolore manga aliuam erat volutpat. Ut isi wnim ad moinim veniam, uis nnostruc exerci tation ullamcorper suspicit.
        background-color: transparent
        image:
        cta:
          label: Click Here
          url:
          background-color: '#aacb65'
          text-color: '#2c2c30'
          width: 177

    - label: Link Card list with Images ~
      icon: view_list
      comment: Stacked cards with image on left and title & description on right.
      value:
        _type: link_list_with_images
        headline:
        cta:
          label: Explore All Initiatives
          url: https://lab.cr.org/initiatives/
          background-color: '#2c2c30'
          text-color: '#aacb65'
          width: 177
        cards:
          - headline:
            description:
            image:
    - label: Team Member Spotlight ~
      icon: account_circle
      comment: Features a team member with an image
      value:
        _type: teammember_spotlight
        name:
        image:
    - label: Events ~
      icon: event
      comment: Events List
      value:
        _type: events
        image:
    - label: Articles ~
      icon: article
      comment: Single Column Content Section
      value:
        _type: articles
        block_html:
    - label: List of links on right with headline on left ~
      icon: link
      comment: Two Column Images
      value:
        _type: link_list_with_dates
        images:

