# ATTENTION: ALL CLOUDCANNON CMS CONFIGURATION NOW LIVES IN cloudcannon.config.yml

# ------------------------------------------------
# DEFINE GLOBAL VARIABLES
# ------------------------------------------------

# Site settings
client: TBD
title: Ocupop Email Builder
description: A tool for building HTML emails which can then be pasted into your CRM of choice
email: dev@ocupop.com
url: "http://localhost:4000"
permalink: pretty

# Social sharing
socialshare:
  featured_image:
  twitter:
    username:
    image:

# Google Analytics
analytics:
  default:

placeholder_image: https://via.placeholder.com/1000x1000/333333/000000?text=Placeholder


# ------------------------------------------------
# DEFINE COLLECTIONS
# (All CloudCannon CMS config is set in cloudcannon.config.yml)
# ------------------------------------------------
collections:
  newsletters:
    output: true
    permalink: /innovationlab-newsletters/:path/



# ------------------------------------------------
# DEFINE DEFAULT VALUES
# (useful for setting layout for page types without having them editable by the user)
# ------------------------------------------------
defaults:
  -
    scope:
      type: 'page'
    values:
      layout: default
  -
    scope:
      type: 'post'
    values:
      layout: default
  -
    scope:
      type: 'newsletters'
    values:
      layout: newsletter_default
      # variable_name: value


# ------------------------------------------------
# BUILD SETTINGS AND PLUGINS
# ------------------------------------------------
safe: false
sass:
  # style: compressed
  sass_dir: _scss
plugins:
  - jekyll-sitemap


